{% set version = "0.76.0" %}

package:
  name: evalml-core
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/e/evalml/evalml-{{ version }}.tar.gz
  sha256: 034796aa662d7ee5f4e530aa5b0b86248a35fd943979694688172d062e25f2a6
build:
  number: 0

outputs:
  - name: evalml-core
    build:
      entry_points:
        - evalml = evalml.__main__:cli
      noarch: python
    script: build_script.sh
    requirements:
      host:
        - python >=3.8,<3.10
        - pip
      run:
        - numpy <=1.23.5,>=1.21.0
        - pandas >=1.5.0
        - dask >=2022.2.0,!=2022.10.1
        - scipy >=1.5.0
        - scikit-learn >=1.2.2
        - scikit-optimize >=0.9.0
        - statsmodels >=0.12.2
        - colorama >=0.4.4
        - cloudpickle >=1.5.0
        - click >=8.0.0
        - shap >=0.40.0
        - texttable >=1.6.2
        - woodwork >=0.22.0
        - featuretools>=1.16.0
        - nlp-primitives >=2.9.0
        - python >=3.8.*
        - networkx >=2.6
        - category_encoders >=2.2.2, <=2.5.1.post0
        - python-graphviz >=0.13
        - tomli >=2.0.1
        - black[jupyter] >=22.3.0
        - packaging >=23.0
        - holidays<0.21,>=0.13
    test:
      imports:
        - evalml
      requires:
        - pytest ==6.0.1
        - nbval ==0.9.3
      source_files:
        - evalml/*
        - pyproject.toml
      commands:
        - pytest evalml/tests -n 8 --ignore evalml/tests/automl_tests/parallel_tests/ --has-minimal-dependencies

  - name: evalml
    build:
      noarch: python
    requirements:
      run:
        - '{{ pin_subpackage("evalml-core", max_pin="x.x.x.x") }}'
        - plotly >=5.0.0
        - python-kaleido >=0.1.0
        - matplotlib-base >=3.3.3
        - seaborn >=0.11.1
        - ipywidgets<8.0.5,>=7.5
        - xgboost >=1.7.0
        - catboost>=1.1.1
        - lightgbm >=2.3.1
        - python >=3.8.*
        - imbalanced-learn >=0.9.1
        - sktime ==0.17.0
        - lime>=0.2.0.1
        - vowpalwabbit>=8.11.0
        - pmdarima>=1.8.5
    test:
      imports:
        - evalml
      requires:
        - pytest ==6.0.1
        - nbval ==0.9.3
        - python-graphviz >=0.8.4
        - category_encoders >=2.0.0
        - pytest-xdist
      source_files:
        - evalml/*
        - pyproject.toml
      commands:
        - pytest evalml/tests -n 8 --ignore evalml/tests/automl_tests/parallel_tests/ --is-using-conda

about:
  doc_url: https://evalml.featurelabs.com/
  dev_url: https://github.com/alteryx/evalml/
  home: https://www.alteryx.com/open-source
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: EvalML is an AutoML library that builds, optimizes, and evaluates machine learning pipelines using domain-specific objective functions.

extra:
  recipe-maintainers:
    - machineAYX
    - dsherry
    - freddyaboulton
    - ParthivNaresh
    - bchen1116
    - chukarsten
    - jeremyliweishih
    - christopherbunn
    - eccabay
    - fjlanasa
    - MichaelFu512
    - ivanayx
