{% set version = "0.13.0.dev0" %}

package:
  name: evalml-core
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/57/a8/5eac8703f7d302d63831a2e501a6a39aa2a6350d8849cb3729bea3ced2e4/evalml-0.13.0.dev0.tar.gz
  sha256: 87af4eb7c64c5499c32860f9a5fc19b6b074a86603126282cc6bc123b766c7fc

build:
  number: 1

outputs:
  - name: evalml-core
    build:
      entry_points:
          - evalml = evalml.__main__:cli
      noarch: python
    script: build_script.sh
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - numpy >=1.16.4
        - pandas >=0.25.0
        - scipy >=1.2.1
        - scikit-learn >=0.21.3,!=0.22,<0.23.0
        - scikit-optimize
        - tqdm >=4.33.0
        - colorama
        - cloudpickle >=0.2.2
        - click >=7.0.0
        - psutil >=5.6.3
        - requirements-parser >=0.2.0
        - shap >=0.35.0
        - texttable >=1.6.2
        - python >=3.6.*
    test:
      imports:
        - evalml
      requires:
        - pytest >= 4.4.*
        - nbval ==0.9.3
        - python-graphviz >=0.8.4
        - category_encoders >=2.0.0
        - featuretools
        - nlp-primitives >=1.0.0
      source_files:
        - evalml/*
        - requirements.txt
        - core-requirements.txt
      commands:
        - pytest evalml/tests --has-minimal-dependencies

  - name: evalml
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('evalml-core', max_pin="x.x.x.x") }}
        - plotly >=4.2.1
        - ipywidgets >=7.5
        - py-xgboost >=0.82
        - catboost >=0.20
        - python >=3.6.*
    test:
      imports:
        - evalml
      requires:
        - pytest ==4.4.1
        - nbval ==0.9.3
        - python-graphviz >=0.8.4
        - category_encoders >=2.0.0
        - featuretools
        - nlp-primitives >=1.0.0
      source_files:
        - evalml/*
        - requirements.txt
        - core-requirements.txt
      commands:
        - pytest evalml/tests

about:
  doc_url: https://evalml.featurelabs.com/en/stable/
  dev_url: https://github.com/Featuretools/featuretools/
  home: https://www.alteryx.com/innovation-labs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: EvalML is an AutoML library that builds, optimizes, and evaluates machine learning pipelines using domain-specific objective functions.

extra:
  recipe-maintainers:
    - dsherry
    - freddyaboulton
