{% set version = "0.64.0" %}

package:
  name: evalml-core
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/e/evalml/evalml-{{ version }}.tar.gz
  sha256: 614e4f36de3bdbea6142686424d627e29c68339f1e6a8a26a08d45e493d7b402
build:
  number: 0

outputs:
  - name: evalml-core
    build:
      entry_points:
        - evalml = evalml.__main__:cli
      noarch: python
    script: build_script.sh
    requirements:
      host:
        - python >=3.8,<3.10
        - pip
      run:
        - numpy >=1.21.0
        - pandas >=1.4.0
        - dask !=2022.10.1,>=2022.2.0 
        - scipy >=1.5.0
        - scikit-learn >=1.1.2
        - scikit-optimize >=0.9.0
        - statsmodels >=0.12.2
        - colorama >=0.4.4
        - cloudpickle >=1.5.0
        - click >=7.1.2
        - requirements-parser >=0.2.0
        - shap >=0.40.0
        - texttable >=1.6.2
        - woodwork !=0.20.0,>=0.19.0
        - featuretools>=1.16.0
        - nlp-primitives >=2.9.0
        - python >=3.8.*
        - networkx >=2.5,<2.6
        - category_encoders >=2.2.2
        - python-graphviz >=0.13
    test:
      imports:
        - evalml
      requires:
        - pytest ==6.0.1
        - nbval ==0.9.3
      source_files:
        - evalml/*
        - setup.cfg
      commands:
        - pytest evalml/tests -n 8 --ignore evalml/tests/automl_tests/parallel_tests/ --has-minimal-dependencies

  - name: evalml
    build:
      noarch: python
    requirements:
      run:
        - '{{ pin_subpackage("evalml-core", max_pin="x.x.x.x") }}'
        - plotly >=5.0.0
        - python-kaleido >=0.1.0
        - matplotlib-base >=3.3.3
        - seaborn >=0.11.1
        - ipywidgets >=7.5
        - xgboost >=1.5.1
        - catboost >=0.20
        - lightgbm >=2.3.1
        - python >=3.8.*
        - imbalanced-learn >=0.9.1
        - sktime >=0.12.0,<0.13.1
        - lime>=0.2.0.1
        - vowpalwabbit>=8.11.0
        - pmdarima>=1.8.5,<2.0.0
    test:
      imports:
        - evalml
      requires:
        - pytest ==6.0.1
        - nbval ==0.9.3
        - python-graphviz >=0.8.4
        - category_encoders >=2.0.0
        - pytest-xdist
      source_files:
        - evalml/*
        - setup.cfg
      commands:
        - pytest evalml/tests -n 8 --ignore evalml/tests/automl_tests/parallel_tests/ --is-using-conda

about:
  doc_url: https://evalml.featurelabs.com/
  dev_url: https://github.com/alteryx/evalml/
  home: https://www.alteryx.com/open-source
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: EvalML is an AutoML library that builds, optimizes, and evaluates machine learning pipelines using domain-specific objective functions.

extra:
  recipe-maintainers:
    - machineAYX
    - dsherry
    - freddyaboulton
    - ParthivNaresh
    - bchen1116
    - chukarsten
    - jeremyliweishih
    - christopherbunn
    - eccabay
    - fjlanasa
    - MichaelFu512
    - ivanayx
