{% set version = "0.13.2" %}

package:
  name: evalml-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/evalml/evalml-{{ version }}.tar.gz
  sha256: 32bd9396a12d0c87a16c7209f9eeb28b6daee9c2943d5099699add0c6ada806b

build:
  number: 0

outputs:
  - name: evalml-core
    build:
      entry_points:
        - evalml = evalml.__main__:cli
      noarch: python
    script: build_script.sh
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - numpy >=1.16.4
        - pandas >=0.25.0
        - scipy >=1.2.1
        - scikit-learn >=0.21.3,!=0.22,<0.23.0
        - scikit-optimize >=0.7,<=0.7.4
        - colorama
        - cloudpickle >=0.2.2
        - click >=7.0.0
        - psutil >=5.6.3
        - requirements-parser >=0.2.0
        - shap >=0.35.0
        - texttable >=1.6.2
        - python >=3.6.*
    test:
      imports:
        - evalml
      requires:
        - pytest >= 4.4.*
        - nbval ==0.9.3
        - python-graphviz >=0.8.4
        - category_encoders >=2.0.0
        - featuretools
        - nlp-primitives >=1.0.0
      source_files:
        - evalml/*
        - requirements.txt
        - core-requirements.txt
      commands:
        - pytest evalml/tests --has-minimal-dependencies

  - name: evalml
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('evalml-core', max_pin="x.x.x.x") }}
        - plotly >=4.2.1
        - ipywidgets >=7.5
        - py-xgboost >=0.82
        - catboost >=0.20
        - lightgbm >=2.3.1
        - python >=3.6.*
    test:
      imports:
        - evalml
      requires:
        - pytest ==4.4.1
        - nbval ==0.9.3
        - python-graphviz >=0.8.4
        - category_encoders >=2.0.0
        - featuretools
        - nlp-primitives >=1.0.0
      source_files:
        - evalml/*
        - requirements.txt
        - core-requirements.txt
      commands:
        - pytest evalml/tests

about:
  doc_url: https://evalml.featurelabs.com/en/stable/
  dev_url: https://github.com/Featuretools/featuretools/
  home: https://www.alteryx.com/innovation-labs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: EvalML is an AutoML library that builds, optimizes, and evaluates machine learning pipelines using domain-specific objective functions.

extra:
  recipe-maintainers:
    - dsherry
    - freddyaboulton
