conda_forge_output_validation: true
provider:
  linux: default
  linux_aarch64: default
  osx: default
  win: default
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
